language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 7
  - node
after_success:
  - npm run build && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
